version: '3'

services:
  strapi:
    build:
      dockerfile: Dockerfile
      context: ./strapi
    volumes:
      - ./strapi:/strapi
      - /strapi/node_modules
      - ./data:/strapi/.tmp
    ports:
      - '1337:1337'
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    ports:
      - '3000:3000'
    tty: true
