version: '3'

services:
  strapi:
    build: ./strapi
    volumes:
      - ./strapi:/srv/app
      - ./data:/srv/app/.tmp
    ports:
      - '1337:1337'
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app/frontend
    command: sh -c 'cd frontend && yarn start'
    ports:
      - '3000:3000'
    tty: true
